---
- name: OP un joueur via RCON
  hosts: localhost
  gather_facts: false
  vars:
    container_name: "lucas"
    command: "op Ronald_leClown"
  
  tasks:
    - name: Récupérer le mot de passe RCON
      ansible.builtin.shell:
        cmd: "docker exec {{ container_name }} grep 'rcon.password=' /minecraft/server.properties | cut -d'=' -f2"
      register: rcon_password
      
    - name: Envoyer la commande OP via RCON
      ansible.builtin.shell:
        cmd: "docker exec {{ container_name }} mcrcon -H localhost -P 25575 -p '{{ rcon_password.stdout }}' '{{ command }}'"
      register: op_result
              
    - name: Vérifier dans les logs
      ansible.builtin.command:
        cmd: "docker logs {{ container_name }} --tail 5"
      register: logs
      
    - name: Logs du serveur
      ansible.builtin.debug:
        var: logs.stdout_lines